export enum FileCategory {
  PASSPORT_MAIN_PAGE = 'PASSPORT_MAIN_PAGE',
  PASSPORT_REGISTRATION_PAGE = 'PASSPORT_REGISTRATION_PAGE',
  FACE_PHOTO = 'FACE_PHOTO',
  DOCUMENT_ATTACHMENT = 'DOCUMENT_ATTACHMENT',
  REPORT_EXPORT = 'REPORT_EXPORT',
}
